apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-auth-external
  namespace: intellisia-main-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-auth
    creationPolicy: Owner
  data:
  - secretKey: url
    remoteRef:
      key: intellisia/db-creds
      property: url